version: "3.0"

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    volumes:
      - wp_volume:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception_network

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - db_volume:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp_volume:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception_network

volumes:
  db_volume:
  wp_volume:
    driver: local
    driver_opts:
      type: volume
      device: /Users/yubin/desktop/42-Cursus/05-inception/srcs/requirements/tools/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge