version: "3.8"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html/wordpress
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception_network

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception_network

volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: volume
      device: /Users/yubin/desktop/42-Cursus/05-inception/srcs/requirements/tools/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge
