 = replace

CC = c++
CFLAGS = -std=c++98 -Wall -Wextra -Werror

SRC = main.cpp

OBJ = $(SRC:.cpp=.o)

all: $()
.PHONY: all

$(): $(OBJ)
	$(CC) $(CFLAGS) -o $() $(OBJ)

clean:
	rm -f $(OBJ)
.PHONY: clean

fclean: clean
	rm -f $()
.PHONY: fclean

re:
	$(MAKE) fclean
	$(MAKE) all
.PHONY: re
