
## 시크릿으로 repository를 등록할 수 있다 . 
# 
apiVersion: v1
kind: Secret
metadata:
  name: my-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ghonman2/yubchoi-inception.git 
    # user가 필요하다면 이렇게username: my-userNmae
    # paossword가 필요하면 이렇게  passsword: my-password

