apiVersion: networking.k8s.io/v1
kind: Ingress   #ingress = loadbanlancer + nginx
metadata:
  name: app-one-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # 뒤에 있는 uri를 어떻게 보낼 것인가에 대한 이야기임.
spec:
  rules:
    - host: app1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-one-svc
                port:
                  number: 80
